export const fabStyle = {
  alignItems: 'left',
  display: 'inline-flex',
  flexDirection: 'column',
  marginRight: '8px',
  backgroundColor: '#00B5EF',
  color: '#fff',
  width: '40px',
  height: '40px',
  boxShadow: 'none',
  small: {
    marginRight: '8px',
    backgroundColor: '#00B5EF',
    color: '#fff',
    width: '30px',
    height: '30px',
    boxShadow: 'none',
  },
  red: {
    marginRight: '8px',
    backgroundColor: 'red',
    color: '#fff',
    width: '30px',
    height: '30px',
    boxShadow: 'none',
  },
};

export const buttonStyle = {
  standard: {
    width: '200px',
    height: '40px',
    alignItems: 'center',
    display: 'inline-flex',
    flexDirection: 'column',
    margin: '10px 10px',
    backgroundColor: '#00B5EF',
    color: '#fff',
    fontSize: '14px',
    fontWeight: 'bold',
    justifyContent: 'center',
    boxShadow: 'none',
    borderRadius: '4px',
    small: {
      width: '100px',
      height: '40px',
      alignItems: 'center',
      display: 'inline-flex',
      flexDirection: 'column',
      margin: '5px 5px',
      backgroundColor: '#00B5EF',
      color: '#fff',
      fontSize: '14px',
      fontWeight: 'bold',
      justifyContent: 'center',
      boxShadow: 'none',
      borderRadius: '4px',
    },
    social: {
      alignSelf: 'flex-end',
    },
  },
  nomargin: {
    width: '200px',
    height: '40px',
    alignItems: 'center',
    display: 'inline-flex',
    flexDirection: 'column',
    backgroundColor: '#00B5EF',
    color: '#fff',
    fontSize: '1rem',
    fontWeight: 'bold',
    justifyContent: 'center',
    boxShadow: 'none',
    borderRadius: '4px',
  },
  gray: {
    width: '200px',
    height: '40px',
    alignItems: 'center',
    display: 'inline-flex',
    flexDirection: 'column',
    margin: '10px 10px',
    backgroundColor: '#cccccc',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 'bold',
    justifyContent: 'center',
    boxShadow: 'none',
    borderRadius: '4px',
    small: {
      width: '100px',
      height: '40px',
      alignItems: 'center',
      display: 'inline-flex',
      flexDirection: 'column',
      margin: '5px 5px',
      backgroundColor: '#cccccc',
      color: '#fff',
      fontSize: '14px',
      fontWeight: 'bold',
      justifyContent: 'center',
      boxShadow: 'none',
      borderRadius: '4px',
    },
  },
  red: {
    width: '200px',
    height: '40px',
    alignItems: 'center',
    display: 'inline-flex',
    flexDirection: 'column',
    margin: '10px 10px',
    backgroundColor: '#FF0000',
    color: '#fff',
    fontSize: '14px',
    fontWeight: 'bold',
    justifyContent: 'center',
    boxShadow: 'none',
    borderRadius: '4px',
    small: {
      width: '100px',
      height: '40px',
      alignItems: 'center',
      display: 'inline-flex',
      flexDirection: 'column',
      margin: '5px 5px',
      backgroundColor: '#FF0000',
      color: '#fff',
      fontSize: '14px',
      fontWeight: 'bold',
      justifyContent: 'center',
      borderRadius: '4px',
      boxShadow: 'none',
    },
  },
  white: {
    width: '200px',
    height: '40px',
    alignItems: 'center',
    display: 'inline-flex',
    flexDirection: 'column',
    margin: '10px 10px',
    backgroundColor: '#FFFFFF',
    color: '#00B5EF',
    fontSize: '14px',
    fontWeight: 'bold',
    justifyContent: 'center',
    borderRadius: '4px',
    boxShadow: 'none',
    small: {
      width: '100px',
      height: '40px',
      alignItems: 'center',
      display: 'inline-flex',
      flexDirection: 'column',
      margin: '5px 5px',
      backgroundColor: '#FFFFFF',
      color: '#00B5EF',
      fontSize: '14px',
      fontWeight: 'bold',
      justifyContent: 'center',
      borderRadius: '4px',
      border: '8px solid #00B5EF',
      boxShadow: 'none',
    },
  },
};

export const formField = {
  whiteBorder: {
    width: '200px',
    height: '40px',
    textAlign: 'left',
    borderRadius: 'none',
    border: '2px solid #FFF',
    backgroundColor: '#000',
    color: '#FFF',
    fontSize: '16px',
    boxShadow: 'none',
    padding: '10px 10px',
  },
  blackBorder: {
    width: '200px',
    height: '40px',
    textAlign: 'left',
    borderRadius: 'none',
    color: '#000',
    fontSize: '16px',
    boxShadow: 'none',
    margin: '5px 10px',
  },
  wide: {
    width: '350px',
    height: '40px',
    textAlign: 'left',
    borderRadius: 'none',
    border: '2px solid #000',
    backgroundColor: '#FFF',
    color: '#000',
    fontSize: '16px',
    boxShadow: 'none',
    padding: '10px 10px',
    margin: '5px 10px',
  },
};

export const rowCenter = {
  display: 'inline-flex',
  flexDirection: 'row',
  alignItems: 'center',
  padding: '5px 5px',
};
